[project]
name = "simple-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "fastapi[all]>=0.115.12",
  "passlib[bcrypt]>=1.7.4",
  "python-dotenv>=1.1.0",
  "sqlmodel>=0.0.24",
  "bcrypt<4.0",
  "sqlalchemy-libsql>=0.2.0",
]
